### ISSUE TITLE
Claude + Image generation provides two copies of the same image

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#128]
1. Pick Claude 3
2. Pick Dalle-3
3. Ask to create an image

<img width="1026" alt="Monosnap ChatLabs 2024-05-25 22-09-07" src="https://github.com/writingmate/chatlabs/assets/164220685/f510098c-59c8-43c7-a901-0d56d3ddde4e">

**Comment by vood** [comment]
I rewrote Sonnet implementation and it seems to be working
