### ISSUE TITLE
Mark all Pro models for free users

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#133]
As for now, free users don't see which models are free for use and which are locked:

![image](https://github.com/writingmate/chatlabs/assets/164220685/15c4e510-c90e-4224-8e31-b95ea1db0f31)

Add Premium stars ⭐ or Crowns 👑 or Lock 🔒 to the right side of each Pro model for free users

**Comment by PixelVerseIT** [comment]
thats a good idea
