### ISSUE TITLE
Hallucinations while rewriting the text

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#134]
Pick GPT-4o or Claude 3 model

Copy some long text and ask AI to rewrite it.

![telegram-cloud-photo-size-2-5379889946824923941-y](https://github.com/writingmate/chatlabs/assets/164220685/cf71cb1f-c992-4991-b7e6-de2a0a7bce00)

![telegram-cloud-photo-size-2-5370830838595442312-y](https://github.com/writingmate/chatlabs/assets/164220685/11141cd0-580c-4ce6-9305-22b44cde18a8)

**Comment by vood** [comment]
Not happening anymore. Closing
