### ISSUE TITLE
Some users can't login with gmail (Valera's case)

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#137]
![telegram-cloud-photo-size-2-5393456193734828744-y](https://github.com/writingmate/chatlabs/assets/164220685/037af9f9-340a-4ecf-a7f6-656e5571aad7)

Link used from LinkedIn post

https://www.linkedin.com/posts/avysotski_gpt-4o-is-available-on-chatlabs-ex-writingmateai-activity-7196040541707382790-Y-NO?utm_source=share&utm_medium=member_ios

**Comment by vood** [comment]
We've figured it is an outdated webview that is not under our control (Not Chrome Browser or Safari)
