### ISSUE TITLE
A .pdf file cannot be added

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#141]
![image](https://github.com/writingmate/chatlabs/assets/164220685/6f4e7a7b-e327-4411-95f6-93a0f4c43a55)

I tried to add pdf file with english text and couldn't do that

File attached 
[Readability Score Definition .pdf](https://github.com/user-attachments/files/15840364/Readability.Score.Definition.pdf)

**Comment by vood** [comment]
But the error is self explanatory. PDF does not contain any text, and explains what to do if it does not.
