### ISSUE TITLE
Issues with Image Generation Models

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#172]
There are some issue with different text-to-image models and Image Generator turned on as plugins.

Also user review:
_I found a bug but I think you noticed it already or maybe not.
Your service cannot create any image with Stable Diffusion and Flux.1 pro.
I found ChatGPT can generate images but others don't (tested with Mistral Large and Claud 3.5 sonet)._

Tested GPT-4o, Claude 3 Opus, Claude 3.5 Sonnet, Mistral Large:
![image](https://github.com/user-attachments/assets/3fd1c7b7-ace6-42d6-bd93-3970fc4fea4a)

Link
https://docs.google.com/spreadsheets/d/10MD7DMZGIghhqunLilS5JbSlDS7k8qmw7JazWQ9NxdE/edit?usp=sharing

**Comment by vood** [comment]
Added loading messages to intertain the user during 40 seconds and fixed all other stuff
