### ISSUE TITLE
Change icons of assistants

### ISSUE THREAD

**Issue by vood** [writingmate/chatlabs#18]
Icons of Assistants ([image](https://monosnap.com/file/d6zO5badUoHUYkgtUIe7F0zdimLayD)) should be changed to more clear, simple and understandable

Google drive with new icons: [link](https://drive.google.com/drive/u/1/folders/1cA396FovcBkkvZ_gEKHgoO0-APK9Bh-s)

**Comment by DimaKarkanitsa** [comment]
I'll take it

**Comment by rnukala1982** [comment]
@vood  on local, where do i see the icons of assistant?  Is it like default icons?

**Comment by vood** [comment]
This issue is mistakenly marked as good first issue. The icons are saved in the production database and need to be updated there. Without access to the production database it will be hard to do. I will take it on myself. @rnukala1982 do you mind looking at something else? Thanks

**Comment by rnukala1982** [comment]
sure thanks
