### ISSUE TITLE
Pro User: Chats are out of chronological order, unable to continue a chat

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#186]
Issue described by a user:

_I have been an avid user of your AI hosting site for a while now for various tasks and queries, but I've been having consistent issues with chat displays and operations for the site as of late.

Chats or interactions with AI that seem to go for more than two user inputs seem to be displayed completely out of chronological order once the page is refreshed and/or revisited?

For example, I've noticed in nearly all of my previous chats with Claude Sonnet or Gpt 4, that they now display the AI response at the top of the chat history, as if the AI had initiated the chat. And my user inputs have been dotted around the chat in a non-chronological order. It isn't displaying the chat backwards, either.

This issue has consistently lead to many times where I'm unable to continue a chat, as I get error messages such as:

**<img width="384" alt="image (2)" src="https://github.com/user-attachments/assets/7216004e-4d7a-4482-bd34-50f141e6c68c">**

As the chat history has been jumbled up.

I haven't run into this issue until just a week or two or so ago, and the bug has seemingly suddenly come from a past update. I am not too sure if any other users have picked up on this?_

_______

**Customer ID:** 
cus_QXbQgdD7n55T6R

**supabaseUUID**
c653e2fb-a1de-4cea-b2d6-b2fb609509a6

**Comment by vood** [comment]
Fixed
