### ISSUE TITLE
Pro Model + Web Search + Image Generation = No Response/Broken Response

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#198]
Pick GPT-4o + Web Search + Any Image Generation Model

Result: no response

![image](https://github.com/user-attachments/assets/efc2ec1e-9f84-455c-9679-657112981fb4)

**Comment by SergeyVVVV** [comment]
Tried Claude 3.5 Sonnet

Result:

![image](https://github.com/user-attachments/assets/b0b045a7-f337-42cb-8ed8-57ed29656413)

**Comment by SergeyVVVV** [comment]
Claude 3 Opus

![image](https://github.com/user-attachments/assets/b0fcf633-02db-4a10-82be-720af8c5926a)

**Comment by vood** [comment]
fixed in #265
