### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by vood** [writingmate/chatlabs#22]
It is not clear what is ‘Source count’ ([image](https://monosnap.com/file/q2xkzn77T9VYWdPVgoWmlftvzgk9BU)). How to locate this parameter: upload file, choose file, click file [Settings](https://monosnap.com/file/orrQS5gEZrHizAwyB3jQ8MSpPWIWiZ) 
Not clear what file retrieval option ([image](https://monosnap.com/file/X4W2yN0SsReBrZwNhKrWkah6niSGo1))
You cannot remove attached files from chat without using the Left menu ([image](https://monosnap.com/file/ERmCjBy0RmimXqsjJZnjcKF5jJrtwP))

**Comment by SergeyVVVV** [comment]
Solved. Marking as "Done"
