### ISSUE TITLE
Dalle does not generate images

### ISSUE THREAD

**Issue by vood** [writingmate/chatlabs#23]
I’ve reproduced the bug with GPT3.5 and GPT4 Turbo models. Highly possible, that it’s not related to a specific model

The bug is reproduced not every time. Sometimes, especially if it’s 2nd or the following request, Dalle provides an image by a link.

Steps to reproduce:
1. choose gpt 3.5 turbo or gpt4 turbo model
2. turn on Dalle plugin
3. try to generate image

Currently, I catch two behaviours
- GPT 3.5 is unable to generate an image ([example](https://monosnap.com/file/YuFBLjZtEFBbCzLowMZ5YUthcIeeyS))
- GPT 3.5 accepts request but is unable to display an image ([example](https://monosnap.com/file/23pW17u7dbayd6BDdmiGNLpc0QilNh))

**Comment by wilejczuk** [comment]
Can't replicate it, for me, the image is generated and displayed
<img width="731" alt="Screenshot at Apr 02 17-07-36" src="https://github.com/writingmate/chatlabs/assets/50916363/9dc7b103-3249-4517-afd6-54b1ae0731a0">

**Comment by vood** [comment]
Going to close this one until this happens again
