### ISSUE TITLE
Image generation models do not understand: colors, ratio, that text shouldn't be written

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#239]
**GPT 4o + Dalle**
- Wrong color
- ignores instructions about text
https://labs.writingmate.ai/chat/share/64dc8b04-d876-4368-a340-4542be630e4e
![image](https://github.com/user-attachments/assets/d47df5c2-bb93-452d-8fe2-979df4b3008a)

**GPT 4o + Flux**
- Wrong color
- ignores instructions about text
https://labs.writingmate.ai/chat/share/db976729-0c09-4087-8060-e41352ae136a
![image](https://github.com/user-attachments/assets/23a7320b-00ac-46dc-8d2d-0cda5ff27640)

**GPT 4o + Flux**
- Ignores ratio (also, ignores adjective "wide", "squared")
https://labs.writingmate.ai/chat/share/0162eefd-109d-4959-819f-16622b9dba27
![image](https://github.com/user-attachments/assets/f4361d06-56f4-4117-b4f2-90296b8156c5)

**Comment by vood** [comment]
fixed in #265
