### ISSUE TITLE
Dalle doesn't work

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#256]
4o + SD3 and FLUX.1 work.

4o + Dalle:
![image](https://github.com/user-attachments/assets/481380ba-57b8-40d3-99dd-430d1b5686ee)
![image](https://github.com/user-attachments/assets/bf317a8e-525a-4667-935c-248b20b7771a)

Mistral Large + Dalle

![image](https://github.com/user-attachments/assets/f0c1490b-7e51-4604-9eb9-45e352eda8b2)

**Comment by vood** [comment]
fixed
