### ISSUE TITLE
Claude models don't work

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#257]
Claude 3.5 Sonnet
![image](https://github.com/user-attachments/assets/78f861e1-09ec-4038-b815-4b5e01b608e8)

Claude 3 Opus
![image](https://github.com/user-attachments/assets/fc5f489b-f3ea-4f41-b589-267948b6735f)

Haiku
![image](https://github.com/user-attachments/assets/7d23f78d-ce62-4ea4-96eb-abde3ed72fa1)

**Comment by vood** [comment]
Increased Anthropic limits from 2600 to 2700
