### ISSUE TITLE
Login doesn’t work for some users

### ISSUE THREAD

**Issue by vood** [writingmate/chatlabs#26]
Gmail login
- Sometimes an error “access blocked” appears ([image](https://monosnap.com/file/dhZhtHcyfSIe4rwnAAkXNN8Ve5MrLm))
- Sometimes a user is moved back to the Login page ([video](https://www.loom.com/share/06b7c2deff074b188c92625109538efe?sid=d2ff7f76-b3cb-4b86-9ba7-a4d1f3179324))
Email login
- Login link in email doesn’t work

**Comment by SergeyVVVV** [comment]
Not happening now. Closing.
