### ISSUE TITLE
User cannot edit Prompt that includes double braces {{}}

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#37]
Steps to reproduce:
1. Create prompt with double braces. For instance: "Draw a wide plain and minimalistic image related to {{Topic}}, with few elements on it and without text, in warm trending colors"
2. Try to edit description or name of the prompt after the prompt is created

Current result:
User cannot edit prompt name & description, "Enter Prompt Variables" menu pops up

Expected result: 
User can edit prompt name & description, "Enter Prompt Variables" menu does not pop up

**Comment by SergeyVVVV** [comment]
Video: https://www.loom.com/share/a3617f5ddb964db391ac3fe9e0669d47?sid=8a0f702a-9523-4cc4-8577-02ea00a1fab2

**Comment by rnukala1982** [comment]
PR to fix: https://github.com/writingmate/chatlabs/pull/42

**Comment by rnukala1982** [comment]
Completed as it is merged.
