### ISSUE TITLE
EDGE_FUNCTION_INVOCATION_TIMEOUT

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#38]
Asked a question to GPT 4 Turbo with Web Search plugin turned on

Got the result:
An error occurred with your deployment
EDGE_FUNCTION_INVOCATION_TIMEOUT

Screenshot attached
<img width="1383" alt="Monosnap+ChatLabs++2024-03-22+16-53-00" src="https://github.com/writingmate/chatlabs/assets/164220685/2f675913-ac1e-4882-8581-cd22fa3985fa">

**Comment by SergeyVVVV** [comment]
![telegram-cloud-photo-size-2-5192781367316961218-y](https://github.com/writingmate/chatlabs/assets/164220685/6d7c6d48-28e3-479d-8a56-918c57288fb9)

**Comment by vood** [comment]
This should be fixed now
