### ISSUE TITLE
Expouse of Supabase service key in 20240108234540_setup.sql

### ISSUE THREAD

**Issue by thehackergpt** [writingmate/chatlabs#40]
I don't know if the service key inside file "20240108234540_setup.sql" is valid or not, but I recommend removing it and replacing it with something like the variable 'SUPABASE_SERVICE_ROLE_KEY. ' When needed, you can change that variable manually to the actual key inside Supabase UI --> Database --> Functions --> delete_storage_object.

@vood

**Comment by vood** [comment]
Thanks! The api key is not valid. But thanks for reporting!

**Comment by vood** [comment]
Actually, you are right! Thanks
