### ISSUE TITLE
Web Search: Application error

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#41]
Steps to reproduce: 
1. Try to address the question to any web page several times in a row, using any AI model and Web Search plugin turned On.
2. I've caught the bug on GPT-4 Turbo and Mistral Large models, trying to translate/summarize the article (https://barmstrong.medium.com/how-to-hire-executives-e2ee8e05cad3)

Current behaviour: see on the screen below
Expected behaviour: a user is able to get a reply to their message from an AI. 

![Screenshot 2024-03-27 at 18 32 34](https://github.com/writingmate/chatlabs/assets/164220685/dc761f05-6ee0-47ad-bd24-c8252e28443c)

**Comment by vood** [comment]
This is fixed now
