### ISSUE TITLE
Files: Endless loading while address prompt to a file

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#43]
Steps to reproduce:
1. Choose any AI
2. Choose a file and ask AI sth about this file

Current behaviour: endless loading, no result provided

Expected behaviour: AI processes the command and provides a result

Video: https://www.loom.com/share/db9f6a927cb6424a988042017c1013ed?sid=16f58ffe-77b9-4bde-9dc2-a08fa0053982

**Comment by vood** [comment]
Fixed
