### ISSUE TITLE
Files: AI translates web links badly 

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#44]
AI, while translating the the web links, glues, cuts and distorts words

Steps to reproduce:
1. Choose any of Mistral Large, GPT4 Turbo, Claude 3 LLMs
2. Turn Web Search On
3. Ask AI to translate the information from the link

Current behaviour: AI glues, cuts and distorts words
Expected behaviour: Proper translation provided

<img width="1357" alt="Translation issues" src="https://github.com/writingmate/chatlabs/assets/164220685/df969b5b-d7a8-4b84-a49e-21890a1e9869">

**Comment by vood** [comment]
This has been fixed in one of the previous commits
