### ISSUE TITLE
Persistence of Issue #8: Messages Can Be Sent During File Upload

### ISSUE THREAD

**Issue by thehackergpt** [writingmate/chatlabs#48]
Despite the attempted resolution in Issue #8, the application still permits users to send messages while a file is in the process of uploading. This behavior is inconsistent with the expected functionality where message sending should be disabled during uploads to ensure sequential data processing and user experience integrity.

**Comment by vood** [comment]
Thanks for reporting! Saw you are familiar with this codebase :) Contributions are welcome!
