### ISSUE TITLE
Bug: Chat conversation split into separate question-answer threads in left panel

### ISSUE THREAD

**Issue by PiotrSss** [writingmate/chatlabs#50]
The conversation is divided into question-answer pairs and dumped into separate threads in the left panel under the "Chats" tab. I think this problem started yesterday. I thought it might be caused by using different assistants during one conversation, but now I see that this error occurs even when I use only one assistant throughout the conversation. During the conversation everything appears normal in main panel, but after refreshing or switching to different/new thread it becomes impossible to continue previous discussions.

![CleanShot 2024-03-29 at 14 29 17@2x](https://github.com/writingmate/chatlabs/assets/1761204/f9ea1f7f-66be-40bb-9c0e-92f49b4a81a3)
![CleanShot 2024-03-29 at 14 29 37@2x](https://github.com/writingmate/chatlabs/assets/1761204/e80c1ad5-065e-4b71-8cec-a4d201989655)

**Comment by vood** [comment]
@PiotrSss thanks for reporting. This is interesting corner case. I have tried to reproduce it and it does not seem to work for me, but surely something is off. Please report back if this still happening to you and I will investigate further.

**Comment by PiotrSss** [comment]
Yes, all conversations are being split, so it's currently unusable for any use case that requires coming back to past discussions. It doesn't matter if it's a discussion with an assistant or a clean model. Also, if I try to add something to one of the parts that was separated, it gets even weirder:

![CleanShot 2024-03-29 at 17 49 35@2x](https://github.com/writingmate/chatlabs/assets/1761204/2b812ce0-7c4c-416b-8f02-3984b08cb69e)

**Comment by PiotrSss** [comment]
Btw. there are no errors in the dev console, neither when I'm still in the full conversation, nor when I open to the separated part.

**Comment by PiotrSss** [comment]
I'm testing to see when this happens. I deleted all the threads that were split and a few earlier threads to check if there might have been a trigger for this error somewhere, but no, each new conversation is still being split into fragments. BUT I noticed that if I refresh the application after the first question-and-answer pair and go back to this conversation, I can continue it and this error will no longer appear in such conversation. So there is at least a temporary "workaround" for this issue.

**Comment by PiotrSss** [comment]
Oh, I don't need to refresh the entire app. It's enough to click on the thread name in the panel once the AI generates the first response and the thread appears there. This action changes the URL from "/chat" to "/chat/<conv_id>", and everything works as expected.

**Comment by PiotrSss** [comment]
Thank you!
