### ISSUE TITLE
Change Left Menu structure

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#62]
Structurization of the left side menu.

The main idea is to keep Chats section in the tier-1 of UX hierarchy and move Plugins, Files, Assistants, Prompts libraries to the tier-2 (one step 'deeper').

1. Remove left vertical sub-menu with icons 
2. Remove the Chats icon
3. Put icons of sections Prompts, Assistants, Files, Plugins horizontally underneath the New Chat button.
4. Put icons of Profile Settings and Premium Crystal at the bottom 
![image](https://github.com/writingmate/chatlabs/assets/164220685/7f11ef47-4225-4d43-a0cb-295ddd057e17)

Interaction with sections
5. Files sub-section
- Is opened by tapping the Files icon
- the sub-section slides out from the left side of the screen (the same way Profile Settings appear now)
- when opened, 
a) the name of the section "Files" is placed at the top. 
b) the "Close" button is placed in the top right corner that closes the sub-section "Files"
![image](https://github.com/writingmate/chatlabs/assets/164220685/419440dd-03e6-472d-8cd6-634b5f6b99e5)

6. Assistants - same logic as for Files
7. Plugins - same logic as for Files
8. Prompts - same logic as for Files UNTIL https://github.com/writingmate/chatlabs/issues/19 is not done.

Link to the mockup in Figma: https://www.figma.com/file/3cWnVt9tSMoczyUEEKacb1/%F0%9F%94%AE-Writingmate-Design?type=design&node-id=3498-4710&mode=design&t=i18K3vDavkpkXV6c-4

**Comment by yesbhautik** [comment]
Not looks very much good, current menu looks good. And we also have to think about mobile view.

**Comment by yesbhautik** [comment]
> Link to the mockup in Figma: https://www.figma.com/file/3cWnVt9tSMoczyUEEKacb1/%F0%9F%94%AE-Writingmate-Design?type=design&node-id=3498-4710&mode=design&t=i18K3vDavkpkXV6c-4

it's not public link

**Comment by SergeyVVVV** [comment]
Done.

**Comment by SergeyVVVV** [comment]
Done
