### ISSUE TITLE
Mistral Large - Web Search issues while trying to generate image

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#63]
Found the bug with Mistral Large model. Not sure if it is reproduced with other LLMs.

Steps to reproduce
1. Pick Mistral Large model 
2. Turn on "Image Generation" plugin. Do not turn on 'Web Search' Plugin.
3. Put the prompt "Create a wide image showing a robot looking into the window with the picturesque view outside"

Current result:
- LLM provides a blurred image
- Besides the image, LLM shows results similar to what Web Search plugin usually provides (but it's not turned On), with broken links to YouTube videos and resources.

Expected result: 
LLM provides image and nothing more.

Video:
https://www.loom.com/share/6661b12b3e9a44369ac05f3f3295b5bd?sid=6f8ccd20-e459-4b19-8d1d-b1f53cfedd68

![image](https://github.com/writingmate/chatlabs/assets/164220685/0b661089-9593-4051-abd1-24edeebd1dce)

**Comment by vood** [comment]
Thanks, good catch, I enabled image optimization and it messed up with image quality. I also adressed the formatting: wide, tall, square.
