### ISSUE TITLE
Copy text feature: copied text is pasted with extra empty lines

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#87]
1. Copy any message from a chat using "Copy" icon in top right corner.
2. Paste copied text.

Current result: extra empty lines appear

<img width="774" alt="Copy issue" src="https://github.com/writingmate/chatlabs/assets/164220685/e7283b6b-3eb8-4250-8cf7-79005197246d">

**Comment by vood** [comment]
Closed
