### ISSUE TITLE
Mistral Large: Function Calling error 

### ISSUE THREAD

**Issue by SergeyVVVV** [writingmate/chatlabs#93]
1. pick Mistral Large model
2. turn On Web Search plugin
3. ask to summarize the video from youtube (for example https://www.youtube.com/watch?v=jvqFAi7vkBc)

**ChatLabs result**
![image](https://github.com/writingmate/chatlabs/assets/164220685/4a31630c-8229-433e-9a1d-c8c247d76434)

**Response:** 
Function call: [{"name": "webScraper__youtubeCaptions", "arguments": {"parameters": {"videoId": "jvqFAi7vkBc"}}}]

**Le Chat result as a refenrence**
![image](https://github.com/writingmate/chatlabs/assets/164220685/6df836fc-8826-48cd-a2a9-0bad70115976)

**Comment by SergeyVVVV** [comment]
#91

**Comment by vood** [comment]
closing in favor #171
